### PR TITLE
Update to nom 3.0

### PR DESCRIPTION
**Pull request by sdroege**
No changes needed

### CODE REVIEW

**Comment by sdroege** [comment]
@Geal It might make sense to also move be_i24 to nom. If you think that's a good idea, I'll send a pull request your way

**Comment by Geal** [comment]
that was fast :D

Sure, please send a PR for be_i24.

The CI does not pass because apparently, Rust 1.2 did not have `overflowing_add` accessible by default. I'm fine with removing 1.2 from the CI and only supporting from current stable.

**Comment by sdroege** [comment]
Ok, all done :)

**Comment by Geal** [comment]
great!

**Comment by sdroege** [comment]
Also found a bug in nom's le_u24 while at it.

Unrelated, I failed to talk to you at RustFest, but were you experimenting with moving nom to some "impl trait" approach instead of macros at some point? Does it make sense or is there still too much missing on the Rust side to make that a viable alternative?

**Comment by Geal** [comment]
I'm still experimenting, and I think it's much too soon to switch to an impl Trait solution. Basically, the unanswered questions right now:
- does it increase or decrease compilation time?
- does it increase or decrease running time?
- can we have a seamless upgrade path where the code of macros is first replaced with impl trait stuff, then removed later?

But this is something I would have liked to do at the beginning of nom, so I'm planning to switch at some point.

**Comment by sdroege** [comment]
Great, thanks :) And sure, those points all need to be answered and tested carefully. But even apart from that, before "impl trait" is stable there's no point in switching anyway. Might be a good time to start experiments though

**Comment by Geal** [comment]
that's also a huge amount of work :)

**Comment by sdroege** [comment]
Of course :) Someone seriously need to invent longer days ;)

**Pull request merged**
