### PR TITLE
Handling script tags

### LINKED ISSUE #1: script tags
I take this task!

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Still a work in progress. Currently fighting with compiler. Tests should come soon as well.

Fixes #1

### CODE REVIEW

**Comment by sdroege** [comment]
What's the status of this, anything missing here?

**Comment by sdroege** [comment]
I could probably review this in the next days, and add anything that is missing for me / not working for me. @GuillaumeGomez sounds good to you?

**Comment by Geal** [comment]
@sdroege please do, I'll review it. I also have to update to nom 2.0

**Comment by sdroege** [comment]
@geal What do you want to update there? Are you planning to switch the parsers to do_parse!(), or anything else? I have an unfinished branch for that somewhere here, got distracted with other things.

**Comment by sdroege** [comment]
My branch for that is at https://github.com/sdroege/flavors/tree/script_tags , currently working on making it actually work and adding more tests

**Pull request closed without merging**
